---
title: "Plot_Repeats"
author: "Faye Romero"
date: "2023-12-08"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_knit$set(root.dir = '/Users/Faye/Documents/FSJ_genome/repeatlandscape') # Set working directory
```

This is a script to plot a simplified repeat landscape using the output (Kimura distance table) from the RepeatMasker util script 'calcDivergenceFromAlign.pl'.

## Load packages

```{r}
library(tidyverse)
library(data.table)
library(viridis)
```

## Load files

```{r cars}
# Read in .summary file, which is the output from the RM utils perl script 'calcDivergenceFromAlign.pl'.
rawdata <- read.table(file = "/Users/Faye/Documents/FSJ_genome/repeatlandscape/HifiSal_Dec22_v2_ALLMAPS.postyag_newnames.summary", header = FALSE, stringsAsFactors = FALSE, skip = 6, fill = TRUE)

# Set genome size
genome_size <- 1322553486
```

## Clean files

```{r}
# Set column names
colnames(rawdata) <- c("Class", "Repeat", "absLen", "wellCharLen", "KimuraPerc")

# Clean table
  remove.start <- which(rowSums(rawdata == "Coverage") > 0) # Find the row that contains the word "Coverage", which marks the end of the table we're interested in plotting
  remove.end <- nrow(rawdata) # Last row number
  data2 <- rawdata[-c(remove.start:remove.end), ] # Remove all rows from 'remove.start' to 'remove.end'
  data3 <- data2[!grepl("ARTEFACT", data2$Class),] # Remove ARTEFACT row
  data4 <- data3[!grepl("\\?", data3$Class), ] # Remove any rows with '?'
  
# Delete temporary files
rm(data2, data3, remove.end, remove.start)
```

## Group families

```{r}
# Define a function to simplify Class names based on patterns
simplify_class <- function(class) {
  if (grepl("DNA", class)) {
    return("DNA")
  } else if (grepl("LINE", class)) {
    return("LINE")
  } else if (grepl("LTR", class)) {
    return("LTR")
  } else if (grepl("SINE", class)) {
    return("SINE")
  } else if (grepl("Satellite", class)) {
    return("Satellite")
  } else if (grepl("Unknown", class) || grepl("Unspecified", class)) {
    return("Unknown")
  } else {
    return("Uncategorized")
  }
}

# Apply the function to create a new column "Simple_class"
data5 <- data4 %>%
  mutate(Simple_Class = sapply(Class, simplify_class)) %>%
  filter(Simple_Class != "Uncategorized")

# Delete temporary files
rm(data4)
```

## Round Kimura substitution levels

```{r}
# Make sure numeric columns are numeric
data6 <- data5 %>% mutate_at(c('absLen', 'wellCharLen', 'KimuraPerc'), as.numeric)
# Round Kimura percentage to nearest whole number
data7 <- data6 %>% mutate(across(c('KimuraPerc'), round, 0))
# Delete temporary files
rm(data5, data6)
```

## Calculate percent of the genome

```{r}
# Create a new column titled "PercLength", which calculates the length of each element as a percentage of the total genome size 
data.final <- mutate(data7, PercLength = (absLen/genome_size)*100)
rm(data7)
```

## Create figure

```{r}
# Plot figure
ggplot(data = data.final, aes(x = KimuraPerc, y = PercLength, fill = Simple_Class)) +
  geom_bar(position="stack", stat="identity") +
  scale_fill_viridis(discrete = T, option = "D", direction = -1) +
  theme_classic() +
  labs(x = "Kimura substitution level (CpG adjusted) (%)", y = "Percent of genome (%)", fill = "TE\nClassification") +
  xlim(0, 48) +
  theme(axis.text=element_text(size=13),axis.title =element_text(size=14))

# Save as a pdf to your working directory
# ggsave("repeat_landscape.pdf")
```